-- CREATE TABLE IF NOT EXISTS query_metrics_processed (
--   query_id VARCHAR NOT NULL,
--   deployment_type VARCHAR NOT NULL,
--   instance_id VARCHAR,
--   arrival_timestamp TIMESTAMPTZ NOT NULL,
--   queue_duration_ms BIGINT NOT NULL,
--   compile_duration_ms BIGINT NOT NULL,
--   execution_duration_ms BIGINT NOT NULL,
--   scanned_mb DOUBLE NOT NULL,
--   spilled_mb DOUBLE NOT NULL,
--   execution_start_time TIMESTAMPTZ NOT NULL,
--   execution_end_time TIMESTAMPTZ NOT NULL,
--   duration_seconds DOUBLE NOT NULL,
--   spill_pressure DOUBLE NOT NULL,
--   queued BOOLEAN NOT NULL,
--   queue_score DOUBLE NOT NULL,
--   compile_score DOUBLE NOT NULL,
--   spill_score DOUBLE NOT NULL,
--   scan_score DOUBLE NOT NULL,
--   PRIMARY KEY(query_id, arrival_timestamp)
-- );

-- CREATE TABLE IF NOT EXISTS query_metrics_scores (
--   query_id VARCHAR NOT NULL,
--   arrival_timestamp TIMESTAMPTZ NOT NULL,
--   deployment_type VARCHAR NOT NULL,
--   instance_id VARCHAR,
--   queue_score DOUBLE NOT NULL,
--   compile_score DOUBLE NOT NULL,
--   spill_score DOUBLE NOT NULL,
--   scan_score DOUBLE NOT NULL,
--   PRIMARY KEY(query_id, arrival_timestamp)
-- );

-- CREATE TABLE IF NOT EXISTS query_metrics_bucket_deployment_5m (
--   deployment_type VARCHAR NOT NULL,
--   window_start TIMESTAMPTZ NOT NULL,
--   running_count DOUBLE NOT NULL,
--   queued_count DOUBLE NOT NULL,
--   scanned_mb DOUBLE NOT NULL,
--   spilled_mb DOUBLE NOT NULL,
--   spill_pressure DOUBLE NOT NULL,
--   PRIMARY KEY(deployment_type, window_start)
-- );

-- CREATE TABLE IF NOT EXISTS query_metrics_bucket_instance_5m (
--   deployment_type VARCHAR NOT NULL,
--   instance_id VARCHAR NOT NULL,
--   window_start TIMESTAMPTZ NOT NULL,
--   running_count DOUBLE NOT NULL,
--   scanned_mb DOUBLE NOT NULL,
--   spilled_mb DOUBLE NOT NULL,
--   PRIMARY KEY(deployment_type, instance_id, window_start)
-- );